const PROJECTS = [
  {
    author: "MinhoLee",
    projectTitle: "[YES24] story24",
    frontend: "React.js, Next.js, redux.js",
    backend: "express.js, spring boot",
    infra: "ubuntu, nginx, pm2",
    link: "https://story24.yes24.com/story",
    cm: "gitlab, redmine",
    duration: "2019.10.14 ~ 2020.11.07",
    myjob: "frontend 개발",
  },
  {
    author: "MinhoLee",
    projectTitle: "[Cuinfo] 원격대학협의회",
    frontend: "html, css, javascript",
    backend: "spring",
    infra: "ubuntu, nginx, tomcat",
    link: "http://www.cuinfo.net/home/index.main.action",
    cm: "github, slack",
    duration: "2020.11.14 ~ 2020-11.27",
    myjob: "데이터 이관 작업",
  },
  {
    author: "MinhoLee",
    projectTitle: "[책열매] 한 학기 한권 읽기",
    frontend: "html, css, javascript",
    backend: "eGovFrame",
    infra: "ubuntu, nginx, tomcat",
    link: "https://ireading.kr/",
    cm: "github, slack",
    duration: "2020.11.28 ~ 2021.03.26",
    myjob: "개발 배포 및 서버 구축",
  },
  {
    author: "MinhoLee",
    projectTitle: "[YES24] seymall",
    frontend: "react.js, redux.js",
    backend: "express.js",
    infra: "ubuntu, nginx, pm2",
    link: "http://seymall.yes24.com/",
    cm: "bitbucket, stackedit",
    duration: "2020.12.25 ~",
    myjob: "운영 유지보수",
  },
]

export default PROJECTS
